language: go

go:
  - "1.12"

# magic word to use faster/newer container-based architecture
sudo: false

git:
  # Use a shallow clone to hopefully speed up builds.
  depth: 1

addons:
  apt_packages:
    - graphicsmagick

services:
  - postgresql

cache:
  pip: true

notifications:
  email:
    on_success: never

install:
  - travis_retry go get -u golang.org/x/lint/golint
  - travis_retry pip install --user awscli

before_script:
  # Download any markers that have not yet been committed to Git to save
  # redoing download/resize work.
  - make photographs-download-markers

script:
  # bail after a single failure
  - set -e

  - make

  # deploy development version that includes drafts
  - TARGET_DIR=./public-dev DRAFTS=true make build
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      TARGET_DIR=./public-dev S3_BUCKET=brandur.org-dev make deploy
    fi

  # then deploy production
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      TARGET_DIR=./public S3_BUCKET=brandur.org make deploy
    fi

  - set -e

after_script:
  # Upload any photographs that we processed during this build.
  - make photographs-upload

# Env that allows a build on the master branch to deploy the site
# automatically.
env:
  global:
    - CLOUDFRONT_ID=E2D97SPIHRBCUA
    - GOOGLE_ANALYTICS_ID=UA-47798518-1

    # $AWS_ACCESS_KEY_ID
    - secure: "OI8c7tiqdUaDNeNQMWQAV1szMfYix9DkmWD8Nji4RiorlSX04U9eqdTl1jvqK4sKdjewpmizQAnU3bmFJHvhsP6S7PNGaduqF7cMufH/yRTH0PPx7SoiEUmPVUEUhkB08+7bzcrGqmJD1tpw6Y46ddGwyWiAopL3hzKsZuwYd6EAU9cjzqsvwv7ZFAw5a2/FhGQuogpoCWrGI9ATpauzH7IgCTuRf/Ufm/XKwEGNI+hrDAtVsd3P1aWbofzUvcLoQ7U2nKEFUrmlgJs8XJGlcsXztRvLrIA31mQG8/u5VGSqcfHv+1H229ONg3P9cTCXe1iNC4QG/plQqYxAx1w1WkcxQK3HWiCrRsPktrf09iwPDuNwCE/KlW81txhtNe6gJ5/nGPdk7mF4hzped44i/uuQ68oZy+ebvtwTlKEiV/+uDncYwQKWQOOqHzaLgDX1wWL/EcpwkurTB5XU8U3TdDhmqiQE1NqQdV90rM8HYv5MW0mRjQK+8u23KapbbhOC5M0rqBCltSBZtQSFTstz+P3pz0xMAAbM9jT6lG1O8sYD4++qPgkuk6plx3Civ4abDep24TcxWaHsLMuCuHOlxOQPUfOxIXgSXHoZLaemkVQI9XSb45tr+9qX1raBKh2IRf12w8Z3QIsAxL4Nal37YIWqRxNaMF/srfBwjmXK3+4="

    # $AWS_SECRET_ACCESS_KEY
    - secure: "fB8PU6VavTFxa7u8+ceh/iJXDniwg6uHbKRyVuDzrtnpX54/zO12VLBtNR+kiuiRz5XTB2t1b47uQfPlmkuqV87AzOuEMfCSC3qbUUUk0OvUOwRwmm4eQ3G+TLrjcQAHcJPA8DLqPxd5hn2VCnLO9eBs93Wlyd/OYd6UlmJpNlXHhkgHh0xT0gjHPvrFvPXzvVia57D1MrLcRVr4jzmkxftpxW9peAtBEJ8BgCdCUCquXYLx8ynr5OxAaSNrDz33DY3HeTL0C765QOl56NcUg8WuZYmnt8J2FqjZDI1Lms3zfqfAWTsptYj5QAfBUNp617nl+Vqqi0B5SX5+snLI2+RdDbA4aYdORY15qpfOnyBr+CzspOm32UULAL3u60kmk+7fiG7Fvc1ynC3t0VTz5WK9Ob/ZfA1OMHzzWpkpiuk8qd+NniKajZp146AM5IrtXmRAJRXdTxm0SLLVPu0Bm3UBVfFFFLGCKvtBj+kLqoDPBmvRa/pn92SKyDB1IRn9VYS83hpNTjw5EZar+GpoH6lsDxfELEHZcsroCvq+lDt5mPfOPKckkFuglS0gqcCNRoTkyT+/4s7PWi63Pqs/12qbzvcS4TIh8tud63auvzSfbDo6kpfpqgWJbC8KLcfYwXKXTK3l6BnKdbrSPXw7Z+3UwYJZU3EQnlHNTwrSeEc="

    # $BLACK_SWAN_DATABASE_URL
    - secure: "XHwgOuRKs/NWMOEZMvR/sgTvclpr6pkA2JjcDVkJc7Fjn5AodiImCNCDsV6zRJRimQgekKemCprSNfhn42Jtv4R6n7wDnd06Yl2SqpjH/QlEQoTjxaOiTxnAcQjSDfYX9kuKvOoaxw8QJyq9f0/e2cDJ7rsE89lylm+iOMMlf9HWRwlC5TvqKJHfxbmLoG8CxUgXjChBm7oqCBRiQ9zMSm8x4NvE6yjaS7+FaUWigvBrnRorJxoPAO8ILt7gZbEM7uDZ1Fao0WcL5wqQLmGgzKbisoy52G8z7RBEDw42J6ozSURrMlqHsUDG51C7hnZq2Jlr/QqUaS5HZyPZOkOoKp1CRnagAPYcS5YAbGTUYe8XFcawyPL3FUj+3tUo2gSApmeypUKXp4BL0Tw0fzGuSZQJzDsfz0xSDHcggbUkhdQhFc8DXSBToxS9jW5SVhxmOZanYOl13jXbsBn0l8h5L04y3EqgWRtcCS9s7kQ04+D9J7ne+PfFgZXG2H/PHVIjTxo53dLVNow/e/3vndCLikr2q6BaGhORNsBSUN7/fc8Fx+EUw5tujGeJj55ZwENRjs2c1+o6ovtH5grocAvhWiLprvQvx5EjLlL5mPXN8D9o5jUqJgcGOvo3v2kKeRZ/XiloEN+hLIxGWDsXLidvcUd/yW9Kk/OscJvUJgkLRIA="

before_script:
  - createdb sorg-test
