title = "2020 Light"
#background_image_url = "https://www.dropbox.com/s/16j6qrfsr7dxhjf/L1070618-adjusted.jpg?dl=1"
description = """\
The world of 2020 is small. Not only has globe trotting come to a sudden, ignominous end, but much of the world was ordered to stay to stay within the confines of their own home. Many of us found suddenly found ourselves as full-time remote workers, and we're the lucky ones. Friends, colleagues, and family were banished to spectral sprites on computer screens.

_2020 Light_ is a photography project that involves me shooting close to where I live, in and around San Francisco. I've always felt that my days here were numbered, and along with being a creative outlet to help me stay sane, it'll also serve as a memento for the city after I've gone.

Each entry consists of one (or occasionally a handful) of photos, coupled with short prose. See also [background on _Sequences_](/sequences-project).
\
"""

[[entries]]
  occurred_at = 2020-05-28T04:18:20Z
  slug = "001"
  title = "An aptly named hill"

  description = """\
Friday afternoon -- a view of Twin Peaks from the adjacent hill of Corona ("crown" in Spanish and Latin) Heights. There's a unique charm to San Francisco's densely packed urban plan, running up and down hillsides, architecture doing whatever needs to be done to conform to uneven terrain. But live here too long, and it starts to blend into the background. I stared at this photo for a good long time to remember what it looked like.
\
"""

  [[entries.photographs]]
    original_image_url = "https://www.dropbox.com/s/cob2hkkklo2uvye/L1010564.jpg?dl=1"
    slug = "001"

[[entries]]
  occurred_at = 2020-05-29T05:25:56Z
  slug = "002"
  title = "The tower"

  description = """\
Sutro Tower, almost 1000 feet high, an old TV and radio tower. Quite possibly San Francisco's most notable landmark if you take the Bridge out of the running. Here I caught it near sunset on a day when clouds had settled onto the mountain. The sun's rays hit it from behind. Its skeletal shadow projects forward.
\
"""

  [[entries.photographs]]
    original_image_url = "https://www.dropbox.com/s/bi7fxmzi2bzmdzu/L1000546.JPG?dl=1"
    portrait = true
    slug = "002"

[[entries]]
  occurred_at = 2020-05-31T00:35:51Z
  slug = "003"
  title = "The beach"

  description = """\
Ocean Beach, looking out towards Cliff House. Most things in San Francisco are miniature versions of their counterparts elsewhere -- houses, bars & restaurants, parks. Ocean Beach breaks the mold. Not only is it long -- running 3-4 miles from the Sutro Baths to Fort Funston -- but also _wide_. It takes about five minutes to walk from the Great Highway down to the water. Its sheer size has been a huge boon during the quarantine, with thousands of people visiting on weekends, and all the while able to maintain ample distance from one another.
\
"""

  [[entries.photographs]]
    original_image_url = "https://www.dropbox.com/s/jt2f3961io8hzzw/L1010203.jpg?dl=1"
    slug = "003"

[[entries]]
  occurred_at = 2020-06-11T03:58:20Z
  slug = "004"
  title = "To the cross"

  description = """\
Stairs to the peak of Mount Davidson. Towards nightfall, and on a cloudy evening.
"""

  [[entries.photographs]]
    original_image_url = "https://www.dropbox.com/s/jk4k5hyor4p87ey/L1010425.jpg?dl=1"
    portrait = true
    slug = "004"

