
#
# /nanoglyphs/010-monterey
#

[[photographs]]
  crop_width = 1200
  original_image_url = "https://www.dropbox.com/s/fu9cjjbssl4kyby/L1080497.JPG?dl=1"
  slug = "nanoglyphs/010-monterey/san-carlos"
  title = "San Carlos Beach in Monterey at sunrise."

#
# /nanoglyphs/017-twenty
#

[[photographs]]
  crop_width = 1200
  original_image_url = "https://www.dropbox.com/s/7jxx7zx7e3xalfb/2W4A0137.JPG?dl=1"
  slug = "nanoglyphs/017-twenty/canmore"
  title = "Canmore"

[[photographs]]
  crop_width = 900
  original_image_url = "https://www.dropbox.com/s/q1acfqfnkecpixu/da-vinci.jpg?dl=1"
  slug = "nanoglyphs/017-twenty/da-vinci"
  title = "Da Vinci"

[[photographs]]
  crop_width = 900
  original_image_url = "https://www.dropbox.com/s/778i77mmyh5t8mj/2W4A0146.JPG?dl=1"
  slug = "nanoglyphs/017-twenty/river"
  title = "The Bow River"

[[photographs]]
  crop_width = 1200
  original_image_url = "https://www.dropbox.com/s/1onhi70nuy5q2qw/2W4A0144.JPG?dl=1"
  slug = "nanoglyphs/017-twenty/river-2"
  title = "The Bow River"
